apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31437
        hostPort: 8080
        protocol: TCP
      - containerPort: 30478
        hostPort: 8443
        protocol: TCP
  - role: worker
    labels:
      tier: frontend
  - role: worker
    labels:
      tier: backend
  - role: worker
    labels:
      tier: storage
    extraMounts:
      - hostPath: /tmp/kind-files
        containerPath: /files
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            register-with-taints: "storage=required:NoSchedule"
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16
