apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: default
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: apps.k8s.local
    allowedRoutes:
      namespaces:
        from: Same
  - name: https
    protocol: HTTPS
    port: 443
    hostname: apps.k8s.local
    tls:
      mode: Terminate
      certificateRefs:
        - name: gateway-tls
    allowedRoutes:
      namespaces:
        from: Same
