---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: bitnami
spec:
  encryptedData:
    password: AgC+yyZs8N6l7Y4YbVOfEL8oCmlKQaAWxQbNU6pSUDLi4tn74TI3WpLXREpDHUjdRl3GmieiUwP7X13k9VLHGJp9kLIzrE+AzopdNiu+ECB19Z/3qeNHe1nvPLnJZbvU4B/zhIFO3vY1KB/qiweJdKofxiLjuyIYsc9utCoNkkG3O7IEh/uBij2fMYk3UapGbnvzGvovDc02mbarOr/B/dL/ypz50uDyzfJ01FK+f/xtlfT3OlwOTyVwe7o0KCMuhfiym6Fg5xz02bubRN42YI90vwYu+VF4IQCyjdMjI+HAWDEw21gfsJT1tGxR0O2zMf+U6Jc3lauL+39zxXWqFvbgTqEEKVhs7Uc4FsCn8k9gejwdtwr4fIPZnJphpu0SIe/ybht+Ks8Wgi5nLLujFtK2U3DhyOdcnOFC+FWfzqQHVmkZHRLlxjUXFnzzozHyp7hRo2LTkEZyNqSIPhqChZIEuO62ADjYKyrBaCvCqu1vjrrrpRZWz2BYD1b9afl5XGDvbn2miDNXi3IdEwZ+Car3P88OEGz78bXh4IcVIREtinChaxAdas2GVNSzUpaqncg6UGuARzunc1qMJPpbAAzOCXeGZkqmOatUjq114x4Oix8OSh3vu9QQj9bJiAaYp8TrZHgfBHHi3bd2o8S5bhAvbzuPF0c1b8+/fadxvN27Zo4vHfqq9vAnzYGrVfzPdEPOrjnVJpv40A==
    username: AgDAIYADgjgXgkpj2ROHhggyhkpNXrNmRGIe6pPBdPNqrHkUyKgcpe8nu4mUvtP59KNpjcVICF7+emH9t4ZZCd7OxOuqhxMouh/NUrRPnM17CK/iImxop46OYIMlspSS1Q5xThD0AheSjbv3QGU3ln113AD4bMOXgPTLYIME7zJCgeeaq8Fs6mJLuOCkvcuRsOmohqspnkgmbPbljetlDJgkqQbOZx4U2/oeZ5Ik+M40Hn//fVx8rNXIV4NTOtaHCeRSgxV7ed0qrKtrvRedj28oqlaNoTlExMDXFE3Wf+EJUtlxyOdy9jv29Ggh9LCYENZNdXrGNfGFwtpPlY1YKmzQ7HiAtL5OVOu5LYlvpaorRQ/sZltw1eTIugFbJvF/DiATbhytkSIPs1hQjgjadfJihObPxrcJQy7a3yGYs6VJ/L/QthKY5L4tvpictVRDDrDr5J5G53qW/BtnLw+WL7+FzcMrfZtWejpIXubU4jD0CcbEwHPJkm5OVBHWszgLNzh44OpvmFngXnRvxosYpwdDQA7LMb1AMQxyiw6LoOKG93QxfXVHfE9ZQVMOflws43N1gM+5RHYt6ZqwYZIOGnBvCcPVPnfR34RlVnHUY6u24N4O6Dm3n6eYesC+VSeFBJbX3RyEiArpufM9Yir2MLfHik3PsLqZzNGr6MmiDEPWxwCgslXZfuEkZTzVKlP6yS+x3gGF3A==
  template:
    metadata:
      name: mysecret
      namespace: bitnami
