---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
data:
  password: YWRpdHlhMTIz
  username: YWRpdHlh
kind: Secret
metadata:
  name: nginx-sec
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: content
          emptyDir: {}
      initContainers:
        - name: busybox
          image: busybox:1.28
          restartPolicy: Never
          envFrom:
          - secretRef:
             name: nginx-sec
          command: ["sh", "-c"]
          args:
            - echo "<h1>{$username} {$password}</h1>" > /usr/share/nginx/html/index.html
          volumeMounts:
            - name: content
              mountPath: /usr/share/nginx/html
              readOnly: false
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
          - name: content
            mountPath: /usr/share/nginx/html
            readOnly: false
        envFrom:
        - secretRef:
           name: nginx-sec
status: {}
